[package]
name = "cryptonight"
version = "0.1.0"
authors = ["Bert Peters <bert@bertptrs.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digest = "0.8.1"
itertools = "0.8.0"
sha3 = "0.8.2"

[dev-dependencies]
hex = "0.4.0"
hex-literal = "0.2.1"
